resources:
  - name: source-repo
    type: git
    source:
      uri: https://github.com/brandocorp/chefdk-resource.git
  - name: chefdk-resource-image
    type: docker-image
    source:
      repository: brandocorp/chefdk-resource
      username: {{docker-hub-username}}
      email: {{docker-hub-email}}
      password: {{docker-hub-password}}

jobs:
  - name: build-chefdk-resource-image
    plan:
      - get: source-repo
        trigger: true
      - put: chefdk-resource-image
        params:
          build: source-repo
          tag: version
